bot:
  token: '5369536859:AAEzwC7kB5V38RxlIt_a6jqyo-X6N7PZmu4'
  username: 'MvpKstBot'
  admin_group_id: -1001864449322
server:
  port: 8080
  #spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#  datasource:
#    url: jdbc:postgresql://${DATABASE_URL:ec2-63-35-156-160.eu-west-1.compute.amazonaws.com:5432/ddcg9t2eahct3e}?sslmode=require
#    username: ${DATABASE_USERNAME:sgoznazwtunvfl}
#    password: ${DATABASE_PASSWORD:9fdb693c537bab333b836085c3d5899aa6a06094ece52f687103c29a9c52deff}
#    driver-class-name: org.postgresql.Driver