bot:
  token: ${BOT_TOKEN:5891370170:AAFlCswspHtlsFT6OEH5eJa9C9P7tGYfVuo}
  username: ${BOT_NAME:test_mvp_bot_test_bot}
  admin_group_id: ${BOT_ADMIN_GROUP:-1001864449322}
server:
  port: ${PORT:8080}