bot:
  token: ${BOT_TOKEN:5891370170:AAFlCswspHtlsFT6OEH5eJa9C9P7tGYfVuo}
  username: ${BOT_NAME:test_mvp_bot_test_bot}
  admin_group_id: ${BOT_ADMIN_GROUP:-1001864449322}
server:
  port: ${PORT:8080}
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:ec2-63-35-156-160.eu-west-1.compute.amazonaws.com:5432/ddcg9t2eahct3e}?sslmode=disable
    username: ${DATABASE_USERNAME:sgoznazwtunvfl}
    password: ${DATABASE_PASSWORD:9fdb693c537bab333b836085c3d5899aa6a06094ece52f687103c29a9c52deff}
    driver-class-name: org.postgresql.Driver